--- config.toml.example.orig	2022-10-15 10:05:29 UTC
+++ config.toml.example
@@ -89,7 +89,7 @@ changelog-seen = 2
 
 # Link libstdc++ statically into the rustc_llvm instead of relying on a
 # dynamic version to be available.
-#static-libstdcpp = true
+static-libstdcpp = false
 
 # Whether to use Ninja to build LLVM. This runs much faster than make.
 #ninja = true
